[input]
dir = "Q:/Data/Surveys/HouseholdSurveys/MTC-SFCTA2022/Processed_20240329/01-taz_spatial_join"
hh_filename = "hh-taz_spatial_join.csv"
person_filename = "person-taz_spatial_join.csv"
trip_filename = "trip-taz_spatial_join.csv"

[output]
dir = "Q:/Data/Surveys/HouseholdSurveys/MTC-SFCTA2022/Processed_20240329/02-reformat"
hh_filename = "temp_hrecx.dat"
person_filename = "temp_precx.dat"
trip_filename = "temp_tripx.dat"
